# Workflow to publish docker image on docker-hub
name: push_docker_image


# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" and "dev" branch
  push:
    branches: [ "main", "dev" ,"devops"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_on_s3"
  push_docker_image:
    # The type of runner that the job will run on
    runs-on: docker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
        run: |
          docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
          docker build --pull -t ieferrari/ansible:latest -f dockerfile .
          docker push ieferrari/ansible:latest